import type { Recipe, Category, LifestylePost, Product } from "@/types";

export const SAMPLE_CATEGORIES: Category[] = [
  { id: "1", name: "Starters", slug: "starters", description: "Appetizers and small bites", image: "", order: 1, recipeCount: 1 },
  { id: "2", name: "Mains", slug: "mains", description: "Hearty main courses", image: "", order: 2, recipeCount: 2 },
  { id: "3", name: "Desserts", slug: "desserts", description: "Sweet treats", image: "", order: 3, recipeCount: 1 },
  { id: "4", name: "Snacks", slug: "snacks", description: "Quick bites and breads", image: "", order: 4, recipeCount: 1 },
  { id: "5", name: "Drinks", slug: "drinks", description: "Refreshing beverages", image: "", order: 5, recipeCount: 1 },
];

export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: "1",
    title: "Creamy Butter Chicken",
    slug: "creamy-butter-chicken",
    description: "A rich and creamy butter chicken that's better than takeout. Tender chicken in a velvety tomato-based sauce.",
    personalStory: "This butter chicken recipe is close to my heart. It reminds me of cozy family dinners growing up, where the aroma of spices would fill the entire house.",
    instagramUrl: "",
    category: ["mains"],
    tags: ["chicken", "curry", "comfort food"],
    dietaryTags: ["Halal"],
    mealType: ["dinner", "lunch"],
    specialOccasion: ["date-night"],
    prepTime: 20,
    cookTime: 45,
    servings: 4,
    difficulty: "medium",
    ingredients: [
      { id: "1", amount: "500", unit: "g", name: "chicken breast, cubed" },
      { id: "2", amount: "1", unit: "cup", name: "yogurt" },
      { id: "3", amount: "2", unit: "tbsp", name: "butter" },
      { id: "4", amount: "1", unit: "can", name: "crushed tomatoes" },
      { id: "5", amount: "1", unit: "cup", name: "heavy cream" },
      { id: "6", amount: "2", unit: "tsp", name: "garam masala" },
      { id: "7", amount: "1", unit: "tsp", name: "turmeric" },
      { id: "8", amount: "1", unit: "tsp", name: "cumin" },
      { id: "9", amount: "3", unit: "cloves", name: "garlic, minced" },
      { id: "10", amount: "1", unit: "piece", name: "ginger, grated" },
    ],
    instructions: [
      { step: 1, text: "Marinate chicken in yogurt with turmeric and cumin for at least 30 minutes." },
      { step: 2, text: "In a large pan, melt butter over medium heat. Add garlic and ginger, cook until fragrant." },
      { step: 3, text: "Add marinated chicken and cook until browned on all sides." },
      { step: 4, text: "Pour in crushed tomatoes and garam masala. Simmer for 20 minutes." },
      { step: 5, text: "Stir in heavy cream and cook for another 10 minutes until sauce thickens." },
      { step: 6, text: "Serve hot with naan or basmati rice." },
    ],
    heroImage: "",
    tips: "For extra flavor, marinate the chicken overnight. You can also add a squeeze of lemon juice before serving.",
    nutrition: { calories: 450, protein: 35, carbs: 12, fat: 28 },
    status: "published",
    featured: true,
    rating: { average: 4.8, count: 24 },
    viewCount: 1250,
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-01-15"),
    publishedAt: new Date("2026-01-15"),
  },
  {
    id: "2",
    title: "Refreshing Mango Lassi",
    slug: "refreshing-mango-lassi",
    description: "A cool and creamy mango lassi — the perfect drink for warm days or alongside spicy dishes.",
    personalStory: "Every summer, my mom would make a big batch of mango lassi. It's pure nostalgia in a glass.",
    category: ["drinks"],
    tags: ["mango", "drink", "summer"],
    dietaryTags: ["Vegetarian"],
    mealType: ["lunch", "brunch"],
    specialOccasion: [],
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    difficulty: "easy",
    ingredients: [
      { id: "1", amount: "1", unit: "cup", name: "ripe mango, chopped" },
      { id: "2", amount: "1", unit: "cup", name: "plain yogurt" },
      { id: "3", amount: "0.5", unit: "cup", name: "milk" },
      { id: "4", amount: "2", unit: "tbsp", name: "sugar" },
      { id: "5", amount: "1", unit: "pinch", name: "cardamom powder" },
    ],
    instructions: [
      { step: 1, text: "Add mango, yogurt, milk, sugar, and cardamom to a blender." },
      { step: 2, text: "Blend until smooth and creamy." },
      { step: 3, text: "Pour into glasses and serve chilled." },
    ],
    heroImage: "",
    tips: "Use frozen mango chunks for an extra thick and cold lassi.",
    status: "published",
    featured: true,
    rating: { average: 4.9, count: 18 },
    viewCount: 890,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-02-01"),
    publishedAt: new Date("2026-02-01"),
  },
  {
    id: "3",
    title: "Fluffy Garlic Naan",
    slug: "fluffy-garlic-naan",
    description: "Soft, pillowy naan bread brushed with garlic butter. Perfect for scooping up curries.",
    personalStory: "Nothing beats fresh naan straight from the pan. This is my go-to recipe whenever I make curry.",
    category: ["snacks"],
    tags: ["naan", "bread", "garlic"],
    dietaryTags: ["Vegetarian"],
    mealType: ["dinner", "lunch"],
    specialOccasion: ["eid"],
    prepTime: 90,
    cookTime: 15,
    servings: 6,
    difficulty: "medium",
    ingredients: [
      { id: "1", amount: "3", unit: "cups", name: "all-purpose flour" },
      { id: "2", amount: "1", unit: "tsp", name: "active dry yeast" },
      { id: "3", amount: "1", unit: "tsp", name: "sugar" },
      { id: "4", amount: "0.5", unit: "cup", name: "warm milk" },
      { id: "5", amount: "0.25", unit: "cup", name: "yogurt" },
      { id: "6", amount: "3", unit: "tbsp", name: "butter, melted" },
      { id: "7", amount: "4", unit: "cloves", name: "garlic, minced" },
    ],
    instructions: [
      { step: 1, text: "Dissolve yeast and sugar in warm milk. Let sit for 10 minutes until frothy." },
      { step: 2, text: "Mix flour, salt, yogurt, and yeast mixture. Knead into a soft dough." },
      { step: 3, text: "Cover and let rise for 1 hour until doubled in size." },
      { step: 4, text: "Divide into 6 balls. Roll each into an oval shape." },
      { step: 5, text: "Cook in a hot skillet until bubbles form, then flip." },
      { step: 6, text: "Brush with garlic butter and serve warm." },
    ],
    heroImage: "",
    tips: "For extra soft naan, add a tablespoon of oil to the dough.",
    status: "published",
    featured: true,
    rating: { average: 4.7, count: 32 },
    viewCount: 2100,
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-01-20"),
    publishedAt: new Date("2026-01-20"),
  },
  {
    id: "4",
    title: "Aromatic Chicken Biryani",
    slug: "aromatic-chicken-biryani",
    description: "Layered chicken biryani with fragrant basmati rice, tender spiced chicken, and caramelized onions.",
    personalStory: "Biryani is a celebration dish in our family. Every special occasion calls for a big pot of biryani.",
    category: ["mains"],
    tags: ["biryani", "rice", "chicken"],
    dietaryTags: ["Halal"],
    mealType: ["dinner", "lunch"],
    specialOccasion: ["eid", "ramadan"],
    prepTime: 30,
    cookTime: 60,
    servings: 6,
    difficulty: "hard",
    ingredients: [
      { id: "1", amount: "500", unit: "g", name: "chicken, bone-in pieces" },
      { id: "2", amount: "2", unit: "cups", name: "basmati rice, soaked" },
      { id: "3", amount: "3", unit: "whole", name: "onions, thinly sliced" },
      { id: "4", amount: "1", unit: "cup", name: "yogurt" },
      { id: "5", amount: "1", unit: "tsp", name: "saffron in warm milk" },
      { id: "6", amount: "2", unit: "tsp", name: "biryani masala" },
    ],
    instructions: [
      { step: 1, text: "Fry onions until deep golden brown. Set aside." },
      { step: 2, text: "Marinate chicken with yogurt, spices, and half the fried onions." },
      { step: 3, text: "Par-boil rice with whole spices until 70% cooked. Drain." },
      { step: 4, text: "Layer chicken and rice in a heavy pot. Top with saffron milk and remaining onions." },
      { step: 5, text: "Seal pot tightly and cook on low heat for 25 minutes (dum)." },
      { step: 6, text: "Gently mix layers and serve with raita." },
    ],
    heroImage: "",
    tips: "The key to great biryani is patience — let it cook slowly on low heat for the flavors to develop.",
    nutrition: { calories: 550, protein: 30, carbs: 65, fat: 18 },
    status: "published",
    featured: true,
    rating: { average: 4.9, count: 45 },
    viewCount: 3200,
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-02-10"),
    publishedAt: new Date("2026-02-10"),
  },
  {
    id: "5",
    title: "Classic Gulab Jamun",
    slug: "classic-gulab-jamun",
    description: "Soft, syrup-soaked gulab jamun — the king of desi desserts.",
    personalStory: "No celebration is complete without gulab jamun. These little golden balls of happiness are pure joy.",
    category: ["desserts"],
    tags: ["dessert", "sweet", "traditional"],
    dietaryTags: ["Vegetarian"],
    mealType: ["dinner"],
    specialOccasion: ["eid", "ramadan"],
    prepTime: 20,
    cookTime: 30,
    servings: 12,
    difficulty: "medium",
    ingredients: [
      { id: "1", amount: "1", unit: "cup", name: "milk powder" },
      { id: "2", amount: "0.25", unit: "cup", name: "all-purpose flour" },
      { id: "3", amount: "2", unit: "tbsp", name: "ghee" },
      { id: "4", amount: "3", unit: "tbsp", name: "milk" },
      { id: "5", amount: "1.5", unit: "cups", name: "sugar" },
      { id: "6", amount: "2", unit: "cups", name: "water" },
      { id: "7", amount: "3", unit: "whole", name: "cardamom pods" },
    ],
    instructions: [
      { step: 1, text: "Make sugar syrup by boiling sugar, water, and cardamom. Set aside." },
      { step: 2, text: "Mix milk powder, flour, and ghee. Add milk gradually to form a soft dough." },
      { step: 3, text: "Roll into small smooth balls (they will expand when fried)." },
      { step: 4, text: "Deep fry on low heat until dark golden brown." },
      { step: 5, text: "Soak fried balls in warm sugar syrup for at least 2 hours." },
    ],
    heroImage: "",
    tips: "Fry on LOW heat — this is the secret to evenly cooked gulab jamun.",
    status: "published",
    featured: false,
    rating: { average: 4.6, count: 15 },
    viewCount: 780,
    createdAt: new Date("2026-02-20"),
    updatedAt: new Date("2026-02-20"),
    publishedAt: new Date("2026-02-20"),
  },
  {
    id: "6",
    title: "Crispy Samosas",
    slug: "crispy-samosas",
    description: "Golden, crispy samosas stuffed with spiced potatoes and peas. The ultimate snack.",
    personalStory: "Samosa Sundays were a thing in our house. The whole family would gather to fold and fry these beauties.",
    category: ["starters"],
    tags: ["samosa", "snack", "fried"],
    dietaryTags: ["Vegetarian", "Vegan"],
    mealType: ["brunch", "lunch"],
    specialOccasion: ["ramadan", "eid"],
    prepTime: 45,
    cookTime: 20,
    servings: 12,
    difficulty: "medium",
    ingredients: [
      { id: "1", amount: "2", unit: "cups", name: "all-purpose flour" },
      { id: "2", amount: "3", unit: "whole", name: "potatoes, boiled and mashed" },
      { id: "3", amount: "0.5", unit: "cup", name: "peas" },
      { id: "4", amount: "1", unit: "tsp", name: "cumin seeds" },
      { id: "5", amount: "1", unit: "tsp", name: "garam masala" },
      { id: "6", amount: "2", unit: "whole", name: "green chilies, chopped" },
    ],
    instructions: [
      { step: 1, text: "Make dough with flour, oil, salt, and water. Rest for 30 minutes." },
      { step: 2, text: "Cook the filling: saut\u00e9 cumin, add potatoes, peas, and spices." },
      { step: 3, text: "Roll dough into circles, cut in half, form cones, and fill." },
      { step: 4, text: "Seal edges with water paste and deep fry until golden." },
      { step: 5, text: "Serve hot with mint chutney and tamarind chutney." },
    ],
    heroImage: "",
    tips: "For extra crispy samosas, double-fry them — once on medium heat, then again on high.",
    status: "published",
    featured: false,
    rating: { average: 4.5, count: 20 },
    viewCount: 1500,
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-01"),
    publishedAt: new Date("2026-03-01"),
  },
];

export const SAMPLE_LIFESTYLE_POSTS: LifestylePost[] = [
  {
    id: "1",
    title: "5 Spices Every Home Cook Needs",
    slug: "5-spices-every-home-cook-needs",
    excerpt: "Stock your spice rack with these five essential spices and you'll be ready to cook almost anything.",
    content: "<p>A well-stocked spice rack is the backbone of great cooking. You don't need fifty jars — just these five essentials will transform your meals.</p><h2>1. Cumin</h2><p>Cumin is the workhorse of South Asian cooking. Its warm, earthy flavor is the foundation of countless curries, dals, and rice dishes.</p><h2>2. Turmeric</h2><p>Beyond its vibrant golden color, turmeric brings a subtle earthiness that rounds out spice blends.</p><h2>3. Garam Masala</h2><p>This warming blend of cinnamon, cardamom, cloves, and more is the finishing touch on many dishes.</p><h2>4. Red Chili Powder</h2><p>Heat is personal. Start with a mild chili powder and work your way up.</p><h2>5. Coriander</h2><p>Ground coriander adds a subtle citrusy sweetness that pairs beautifully with cumin.</p>",
    category: "Kitchen Tips",
    readingTime: 4,
    status: "published",
    createdAt: new Date("2026-02-15"),
    updatedAt: new Date("2026-02-15"),
    publishedAt: new Date("2026-02-15"),
  },
  {
    id: "2",
    title: "The Art of Slow Cooking",
    slug: "the-art-of-slow-cooking",
    excerpt: "In a world of instant everything, slow cooking is a radical act of love. Here's why it's worth the wait.",
    content: "<p>We live in a culture of speed. Quick meals, instant pots, thirty-minute recipes. And while there's nothing wrong with efficiency, something magical happens when you slow down in the kitchen.</p><h2>The Science of Slow</h2><p>Low and slow cooking breaks down tough proteins, caramelizes sugars, and allows spices to fully bloom.</p><h2>It's Meditative</h2><p>There's something deeply calming about stirring a pot, checking on a braise, letting aromas fill your home.</p><h2>Better Flavor, Every Time</h2><p>The difference between a rushed curry and one that's been simmered patiently is night and day.</p>",
    category: "Food Culture",
    readingTime: 3,
    status: "published",
    createdAt: new Date("2026-02-25"),
    updatedAt: new Date("2026-02-25"),
    publishedAt: new Date("2026-02-25"),
  },
  {
    id: "3",
    title: "How I Fell in Love with Cooking",
    slug: "how-i-fell-in-love-with-cooking",
    excerpt: "From watching my mom in the kitchen to sharing recipes with thousands — this is my cooking journey.",
    content: "<p>I didn't always love cooking. As a kid, I was the one sneaking bites, not the one making the food. But somewhere between watching my mom knead dough and the first time I made chai on my own, something clicked.</p><h2>The Beginning</h2><p>My first real dish was scrambled eggs. Nothing fancy, but the feeling of creating something from raw ingredients was addictive.</p><h2>Finding My Style</h2><p>My cooking style is a blend of tradition and curiosity. I respect the classic recipes my family taught me, but I'm not afraid to put my own twist on things.</p><h2>Sharing the Love</h2><p>When I started posting my recipes online, I never expected the response. That's what keeps me going.</p>",
    category: "Cooking Journey",
    readingTime: 5,
    status: "published",
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-01"),
    publishedAt: new Date("2026-03-01"),
  },
  {
    id: "4",
    title: "A Day in My Kitchen",
    slug: "a-day-in-my-kitchen",
    excerpt: "Spoiler: it involves a lot of tasting, a few disasters, and the occasional happy accident.",
    content: "<p>People sometimes ask me how many times I test a recipe before posting it. The honest answer? As many times as it takes to get it right.</p><h2>Morning: Planning</h2><p>Every recipe day starts with a plan. I write out the recipe as I imagine it, list the ingredients, and think through the steps.</p><h2>Afternoon: The First Attempt</h2><p>The first try is always experimental. I follow my written recipe loosely, adjusting as I go. I taste obsessively.</p><h2>The Honest Truth</h2><p>Not every attempt is a winner. But every failure teaches something. And when a recipe finally clicks? There's no better feeling.</p>",
    category: "Behind the Scenes",
    readingTime: 4,
    status: "published",
    createdAt: new Date("2026-03-05"),
    updatedAt: new Date("2026-03-05"),
    publishedAt: new Date("2026-03-05"),
  },
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Signature Biryani Spice Mix",
    slug: "signature-biryani-spice-mix",
    description: "My secret biryani blend — whole spices, perfectly proportioned for the ultimate biryani every time.",
    price: 12.99,
    currency: "USD",
    category: "Spice Mixes",
    inStock: false,
    comingSoon: true,
  },
  {
    id: "2",
    name: "Everyday Curry Powder",
    slug: "everyday-curry-powder",
    description: "A versatile curry blend you'll reach for daily. Works in everything from chicken curry to roasted vegetables.",
    price: 9.99,
    currency: "USD",
    category: "Spice Mixes",
    inStock: false,
    comingSoon: true,
  },
  {
    id: "3",
    name: "FoodWithRuks Cookbook: Vol. 1",
    slug: "foodwithruks-cookbook-vol-1",
    description: "50 of my most-loved recipes in a beautiful hardcover book. Stories, tips, and step-by-step photos.",
    price: 34.99,
    currency: "USD",
    category: "Cookbooks",
    inStock: false,
    comingSoon: true,
  },
  {
    id: "4",
    name: "Wooden Spice Box (Masala Dabba)",
    slug: "wooden-spice-box",
    description: "A handcrafted wooden spice box with 7 compartments. Keep your everyday spices organized.",
    price: 29.99,
    currency: "USD",
    category: "Kitchen Tools",
    inStock: false,
    comingSoon: true,
  },
  {
    id: "5",
    name: "Chai Lover's Blend",
    slug: "chai-lovers-blend",
    description: "Cardamom, cinnamon, ginger, and cloves — pre-mixed for the perfect cup of masala chai.",
    price: 8.99,
    currency: "USD",
    category: "Spice Mixes",
    inStock: false,
    comingSoon: true,
  },
  {
    id: "6",
    name: "FoodWithRuks Apron",
    slug: "foodwithruks-apron",
    description: "A premium cotton apron in sage green with the FoodWithRuks logo. Looks good, cooks better.",
    price: 24.99,
    currency: "USD",
    category: "Merch",
    inStock: false,
    comingSoon: true,
  },
];
